lisa-directory: ./../lisa_vissim_addon

OWL322:
  id:
    lisa_id: z12_fg12
    sumo_id: OWL322
  signal:
    lisa_sgr_seq: K01, K02, K03, KL03, K04, F51, BT51, BL51, F52, BT52, BL52, F53, BT53, BL53, F54, BT54, BL54
    lisa_sumo_mapping:
      K01: 0, 1, 2, 3, 4, 5
      K02: 6, 7, 8, 9, 10, 11
      K03: 12, 13, 15, 16
      KL03: 14, 17
      K04: 18, 19, 20, 21, 22
      F51: 23
      BT51: -1
      BL51: -1
      F52: 24
      BT52: -1
      BL52: -1
      F53: 25
      BT53: -1
      BL53: -1
      F54: 26
      BT54: -1
      BL54: -1
